monolog:
    channels:
        - deprecation

# DEV
when@dev:
    monolog:
        handlers:
            # osobny plik dla deprecations
            deprecation:
                type: stream
                path: "%kernel.logs_dir%/deprecations.log"
                level: info
                channels: [deprecation]
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!deprecation"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!deprecation"]

# TEST
when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event", "!deprecation"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

# PROD
when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!deprecation"]
                buffer_size: 50
            nested:
                type: stream
                path: php://stderr
                level: error
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!deprecation"]
            # w prod deprecations sÄ… ignorowane
            deprecation:
                type: null