version: '3.8'

services:
  database:
    container_name: wh_database
    image: mysql:${DB_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - db_data:/var/lib/mysql

  php:
    container_name: wh_php
    build:
      context: .
    ports:
      - '9000:9000'
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST:-no}
    volumes:
      - ./:/var/www/project
      - symfony_var_cache:/var/www/project/var/cache
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database

  nginx:
    container_name: wh_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/project:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
  symfony_var_cache:
  db_data:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
